import type { ResumeCompanyResponse } from "./ResumeCompanyResponse";
import type { ResumeAppearanceResponse } from "./ResumeAppearanceResponse";
import type { PersonalLinkResponse } from "../accounts/PersonalLinkResponse";
import type { EducationResponse } from "../education/EducationResponse";
import type { ProjectResponse } from "../projects/ProjectResponse";
import type { SkillResponse } from "../accounts/SkillResponse";
export type ResumeResponse = {
  id: number | null;
  accountId: number;
  resumeName: string;
  aiScore: number | null;
  aiScoreStaleness: string;
  personName: string;
  profession: string;
  email: string;
  phoneNumber: string;
  location: string;
  personalLinks: PersonalLinkResponse[];
  skills: SkillResponse[];
  companies: ResumeCompanyResponse[];
  education: EducationResponse[];
  projects: ProjectResponse[];
  appearance: ResumeAppearanceResponse;
};
