// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResumeTailor.Infrastructure.Persistence;

#nullable disable

namespace ResumeTailor.Infrastructure.Migrations
{
    [DbContext(typeof(ResumeTailorDbContext))]
    partial class ResumeTailorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ResumeTailor.Domain.Accounts.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Auth0UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("ResumeTailor.Domain.Accounts.Bullet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AiScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Bullet", (string)null);
                });

            modelBuilder.Entity("ResumeTailor.Domain.Accounts.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("Ended")
                        .HasColumnType("date");

                    b.Property<bool>("GenerateBullets")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxGeneratedBulletCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Started")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Company", (string)null);
                });

            modelBuilder.Entity("ResumeTailor.Domain.Accounts.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("Ended")
                        .HasColumnType("date");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Started")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseForResume")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Education", (string)null);
                });

            modelBuilder.Entity("ResumeTailor.Domain.Accounts.PersonalLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("PersonalLink", (string)null);
                });

            modelBuilder.Entity("ResumeTailor.Domain.Accounts.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("Ended")
                        .HasColumnType("date");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Started")
                        .HasColumnType("date");

                    b.Property<string>("TechStack")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseForResume")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Project", (string)null);
                });

            modelBuilder.Entity("ResumeTailor.Domain.Accounts.Title", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Title", (string)null);
                });

            modelBuilder.Entity("ResumeTailor.Domain.Extraction.FieldExtractionDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttributeName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtractionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SiteExtractionDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SiteExtractionDefinitionId");

                    b.ToTable("FieldExtractionDefinition", (string)null);
                });

            modelBuilder.Entity("ResumeTailor.Domain.Extraction.FieldPattern", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FieldExtractionDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FieldExtractionDefinitionId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchPattern")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScopePattern")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FieldExtractionDefinitionId1");

                    b.HasIndex("FieldExtractionDefinitionId", "MatchPattern")
                        .IsUnique();

                    b.HasIndex("FieldExtractionDefinitionId", "Priority")
                        .IsUnique();

                    b.ToTable("FieldPattern", (string)null);
                });

            modelBuilder.Entity("ResumeTailor.Domain.Extraction.SiteExtractionDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PathPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Hostname", "PathPattern", "Version")
                        .IsUnique();

                    b.ToTable("SiteExtractionDefinition", (string)null);
                });

            modelBuilder.Entity("ResumeTailor.Domain.GeneratedResumes.AI.ResumeAiAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("GeneratedResumeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedResumeId")
                        .IsUnique();

                    b.ToTable("ResumeAiAnalysis", (string)null);
                });

            modelBuilder.Entity("ResumeTailor.Domain.GeneratedResumes.AI.ResumeAiInsight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResumeAiAnalysisId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResumeAiAnalysisId1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResumeAiAnalysisId2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResumeAiAnalysisId");

                    b.HasIndex("ResumeAiAnalysisId1");

                    b.HasIndex("ResumeAiAnalysisId2");

                    b.ToTable("ResumeAiInsight", (string)null);
                });

            modelBuilder.Entity("ResumeTailor.Domain.GeneratedResumes.AI.ResumeAiMetaData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("GeneratedResumeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedResumeId")
                        .IsUnique();

                    b.ToTable("ResumeAiMetaData", (string)null);
                });

            modelBuilder.Entity("ResumeTailor.Domain.GeneratedResumes.Content.ResumeBullet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlternativeValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResumeCompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceBulletId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResumeCompanyId");

                    b.ToTable("ResumeBullet", (string)null);
                });

            modelBuilder.Entity("ResumeTailor.Domain.GeneratedResumes.Content.ResumeCompanySelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("GeneratedResumeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedResumeId");

                    b.ToTable("ResumeCompanySelection", (string)null);
                });

            modelBuilder.Entity("ResumeTailor.Domain.GeneratedResumes.Content.ResumeEducationSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EducationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GeneratedResumeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedResumeId");

                    b.ToTable("ResumeEducationSelection", (string)null);
                });

            modelBuilder.Entity("ResumeTailor.Domain.GeneratedResumes.Content.ResumeProjectSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("GeneratedResumeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedResumeId");

                    b.ToTable("ResumeProjectSelection", (string)null);
                });

            modelBuilder.Entity("ResumeTailor.Domain.GeneratedResumes.GeneratedResume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("JobApplicationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobApplicationId")
                        .IsUnique();

                    b.ToTable("GeneratedResume", (string)null);
                });

            modelBuilder.Entity("ResumeTailor.Domain.JobApplications.JobApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("AppliedDate")
                        .HasColumnType("date");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("JobUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkStyle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("JobApplication", (string)null);
                });

            modelBuilder.Entity("ResumeTailor.Domain.Accounts.Bullet", b =>
                {
                    b.HasOne("ResumeTailor.Domain.Accounts.Company", null)
                        .WithMany("Bullets")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ResumeTailor.Domain.Accounts.PersonalLink", b =>
                {
                    b.HasOne("ResumeTailor.Domain.Accounts.Account", null)
                        .WithMany("PersonalLinks")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ResumeTailor.Domain.Accounts.Title", b =>
                {
                    b.HasOne("ResumeTailor.Domain.Accounts.Account", null)
                        .WithMany("Titles")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ResumeTailor.Domain.Extraction.FieldExtractionDefinition", b =>
                {
                    b.HasOne("ResumeTailor.Domain.Extraction.SiteExtractionDefinition", null)
                        .WithMany("Fields")
                        .HasForeignKey("SiteExtractionDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ResumeTailor.Domain.Extraction.FieldPattern", b =>
                {
                    b.HasOne("ResumeTailor.Domain.Extraction.FieldExtractionDefinition", null)
                        .WithMany("Patterns")
                        .HasForeignKey("FieldExtractionDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResumeTailor.Domain.Extraction.FieldExtractionDefinition", "FieldExtractionDefinition")
                        .WithMany()
                        .HasForeignKey("FieldExtractionDefinitionId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldExtractionDefinition");
                });

            modelBuilder.Entity("ResumeTailor.Domain.GeneratedResumes.AI.ResumeAiAnalysis", b =>
                {
                    b.HasOne("ResumeTailor.Domain.GeneratedResumes.GeneratedResume", null)
                        .WithOne("AiAnalysis")
                        .HasForeignKey("ResumeTailor.Domain.GeneratedResumes.AI.ResumeAiAnalysis", "GeneratedResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ResumeTailor.Domain.GeneratedResumes.AI.ResumeAiInsight", b =>
                {
                    b.HasOne("ResumeTailor.Domain.GeneratedResumes.AI.ResumeAiAnalysis", null)
                        .WithMany("Insights")
                        .HasForeignKey("ResumeAiAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResumeTailor.Domain.GeneratedResumes.AI.ResumeAiAnalysis", null)
                        .WithMany("Strengths")
                        .HasForeignKey("ResumeAiAnalysisId1");

                    b.HasOne("ResumeTailor.Domain.GeneratedResumes.AI.ResumeAiAnalysis", null)
                        .WithMany("Weaknesses")
                        .HasForeignKey("ResumeAiAnalysisId2");
                });

            modelBuilder.Entity("ResumeTailor.Domain.GeneratedResumes.AI.ResumeAiMetaData", b =>
                {
                    b.HasOne("ResumeTailor.Domain.GeneratedResumes.GeneratedResume", null)
                        .WithOne("AiMetaData")
                        .HasForeignKey("ResumeTailor.Domain.GeneratedResumes.AI.ResumeAiMetaData", "GeneratedResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ResumeTailor.Domain.GeneratedResumes.Content.ResumeBullet", b =>
                {
                    b.HasOne("ResumeTailor.Domain.GeneratedResumes.Content.ResumeCompanySelection", null)
                        .WithMany("Bullets")
                        .HasForeignKey("ResumeCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ResumeTailor.Domain.GeneratedResumes.Content.ResumeCompanySelection", b =>
                {
                    b.HasOne("ResumeTailor.Domain.GeneratedResumes.GeneratedResume", null)
                        .WithMany("CompanySelections")
                        .HasForeignKey("GeneratedResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ResumeTailor.Domain.GeneratedResumes.Content.ResumeEducationSelection", b =>
                {
                    b.HasOne("ResumeTailor.Domain.GeneratedResumes.GeneratedResume", null)
                        .WithMany("EducationSelections")
                        .HasForeignKey("GeneratedResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ResumeTailor.Domain.GeneratedResumes.Content.ResumeProjectSelection", b =>
                {
                    b.HasOne("ResumeTailor.Domain.GeneratedResumes.GeneratedResume", null)
                        .WithMany("ProjectSelections")
                        .HasForeignKey("GeneratedResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ResumeTailor.Domain.GeneratedResumes.GeneratedResume", b =>
                {
                    b.HasOne("ResumeTailor.Domain.JobApplications.JobApplication", null)
                        .WithOne("GeneratedResume")
                        .HasForeignKey("ResumeTailor.Domain.GeneratedResumes.GeneratedResume", "JobApplicationId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("ResumeTailor.Domain.Accounts.Account", b =>
                {
                    b.Navigation("PersonalLinks");

                    b.Navigation("Titles");
                });

            modelBuilder.Entity("ResumeTailor.Domain.Accounts.Company", b =>
                {
                    b.Navigation("Bullets");
                });

            modelBuilder.Entity("ResumeTailor.Domain.Extraction.FieldExtractionDefinition", b =>
                {
                    b.Navigation("Patterns");
                });

            modelBuilder.Entity("ResumeTailor.Domain.Extraction.SiteExtractionDefinition", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("ResumeTailor.Domain.GeneratedResumes.AI.ResumeAiAnalysis", b =>
                {
                    b.Navigation("Insights");

                    b.Navigation("Strengths");

                    b.Navigation("Weaknesses");
                });

            modelBuilder.Entity("ResumeTailor.Domain.GeneratedResumes.Content.ResumeCompanySelection", b =>
                {
                    b.Navigation("Bullets");
                });

            modelBuilder.Entity("ResumeTailor.Domain.GeneratedResumes.GeneratedResume", b =>
                {
                    b.Navigation("AiAnalysis");

                    b.Navigation("AiMetaData");

                    b.Navigation("CompanySelections");

                    b.Navigation("EducationSelections");

                    b.Navigation("ProjectSelections");
                });

            modelBuilder.Entity("ResumeTailor.Domain.JobApplications.JobApplication", b =>
                {
                    b.Navigation("GeneratedResume");
                });
#pragma warning restore 612, 618
        }
    }
}
