// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResumeTailor.Infrastructure.Persistence;

#nullable disable

namespace ResumeTailor.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ResumeTailorDbContext))]
    [Migration("20260730161552_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ResumeTailor.Domain.Extraction.FieldExtractionDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttributeName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExtractionType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FieldName")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SiteExtractionDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SiteExtractionDefinitionId");

                    b.ToTable("FieldExtractionDefinitions");
                });

            modelBuilder.Entity("ResumeTailor.Domain.Extraction.FieldPattern", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FieldExtractionDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FieldExtractionDefinitionId", "Priority")
                        .IsUnique();

                    b.HasIndex("FieldExtractionDefinitionId", "Pattern")
                        .IsUnique();

                    b.ToTable("FieldPattern", (string)null);
                });

            modelBuilder.Entity("ResumeTailor.Domain.Extraction.SiteExtractionDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PathPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Version")
                        .IsUnique();

                    b.ToTable("SiteExtractionDefinition", (string)null);
                });

            modelBuilder.Entity("ResumeTailor.Domain.Extraction.FieldExtractionDefinition", b =>
                {
                    b.HasOne("ResumeTailor.Domain.Extraction.SiteExtractionDefinition", "SiteExtractionDefinition")
                        .WithMany("Fields")
                        .HasForeignKey("SiteExtractionDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiteExtractionDefinition");
                });

            modelBuilder.Entity("ResumeTailor.Domain.Extraction.FieldPattern", b =>
                {
                    b.HasOne("ResumeTailor.Domain.Extraction.FieldExtractionDefinition", "FieldExtractionDefinition")
                        .WithMany("Patterns")
                        .HasForeignKey("FieldExtractionDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldExtractionDefinition");
                });

            modelBuilder.Entity("ResumeTailor.Domain.Extraction.FieldExtractionDefinition", b =>
                {
                    b.Navigation("Patterns");
                });

            modelBuilder.Entity("ResumeTailor.Domain.Extraction.SiteExtractionDefinition", b =>
                {
                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
